"""Translation dictionaries and helpers."""
translations = {
    "en": {
        "dashboard": "Dashboard",
        "buildings": "Buildings",
        "invoices": "Invoices",
        "suppliers": "Suppliers",
        "expenses": "Expenses",
        "logged_in_as": "Logged in as",
        "stop_server": "🛑 Stop Server",
        "logout": "🚪 Logout",
        "send_invoice_subject": "Invoice for Payment",
        "send_invoice_body": "Dear Resident,\n\nAttached is your payment invoice.\n\nBest regards,\nVaad HaBayit",
        "invoice_email_subject": "📄 Invoice #{invoice_id} from Vaad HaBayit",
        "invoice_email_body": "Dear {resident_name},\n\nAttached is your payment receipt from the building management.",
        "resident": "Resident",
        "apartment": "Apartment",
        "payment_date": "Payment Date",
        "amount_paid": "Amount Paid",
        "thank_you": "Thank you for your payment!",
        "receipt": "Receipt #",
        "date": "Date",
        "resident_name": "Resident Name",
        "payment_method": "Payment Method",
        "for_month": "Payment For",
        "description": "Description",
        "amount": "Amount",
        "line_item": "HOA Fee",
        "total_paid": "Total Paid",
        "thanks": "Thank you for your payment!",
        "contact": "Contact",
        "view_invoice": "👁️ View Invoice",
        "send_invoice": "📤 Send Invoice",
        "download_invoice": "⬇️ Download Invoice",
        "invoice_sent_to": "Invoice #{invoice_id} sent to {email}",
        "invoice_sent_short": "📧 Sent",
        "filter_by_building": "🏢 Filter by Building",
        "filter_by_status": "📌 Filter by Status",
        "filter_by_expense_type": "📂 Filter by Expense Type",
        "filter_by_start_date": "📅 From Start Date",
        "add_expense": "Add Expense",
        "edit_expense": "Edit Expense",
        "delete_expense": "Delete Expense",
        "add_supplier": "Add Supplier",
        "edit_supplier": "Edit Supplier",
        "delete_supplier": "Delete Supplier",
        "view_as_user": "👤 View as User",
        "view_as_admin": "👤 View as Admin",
        "admin_panel": "🔐 Admin Panel",
        "back_to_app": "⬅️ Back to App",
        "assign_buildings": "🏢 Assign buildings",
        "create_account": "➕ Create New User Account",
        "building_added": "Building Added!",
        "building_deleted": "Building '{building}' deleted successfully!",
        "expense_added": "Expense added successfully.",
        "expense_updated": "Expense updated.",
        "expense_deleted": "Expense deleted.",
        "supplier_added": "Supplier added!",
        "supplier_updated": "Supplier updated.",
        "supplier_deleted": "Supplier deleted.",
        "login_title": "Login",
        "signup_title": "Sign Up",
        "username": "Username",
        "password": "Password",
        "new_username": "New Username",
        "new_password": "New Password",
        "email": "Email",
        "assign_role": "Assign Role",
        "create_account_btn": "Create Account",
        "login_btn": "Login",
        "user_created": "User '{username}' created with role '{role}'.",
        "fill_all_fields": "Please fill all fields.",
        "invalid_credentials": "Invalid username or password",
        "welcome_user": "Welcome, {username}","months": [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
],
"your_balance": "Your Balance",
        "total_amount_paid": "Total Amount Paid",
        "transactions": "Tenets payments",
        "my_profile": "My Profile",
        "support": "Support",
        "reports": "Reports",
        "produce_report": "Produce Report",
        "report_type": "Report Type",
        "full_report": "Full Report",
        "transactions_only": "Transactions Only",
        "expenses_only": "Expenses Only",
        "net_balance": "Net Balance",
        "send_invoices_title": "Send Invoices",
        "select_building": "Select Building",
        "please_select_building": "Please select a building to view or send invoices.",
        "year": "Year",
        "month": "Month",
        "quarter": "Quarter",
        "select_apartments_send": "Select Apartments to Send Invoices To",
        "send_selected_invoices": "Send Selected Invoices",
        "please_select_apartment": "Please select at least one apartment.",
        "invoices_sent_success": "{count} invoice(s) sent successfully.",
        "no_paid_transactions": "No paid transactions found for the selected filters.",
        "paid_transactions": "Paid Transactions",
        "transactions_management": "Transactions Management",
        "total_expense_amount": "Total Expense Amount",
        "cumulative_value": "Cumulative",
        "no_expenses_match": "No expenses match the selected filters.",
        "app_title": "🏠 Apartment Management App",
        "app_subtitle": "Here's your latest building data and financial summary.",
        "no_buildings_assigned": "⚠️ No buildings assigned to your account.",
        "from_year": "From Year",
        "from_month": "From Month",
        "to_year": "To Year",
        "to_month": "To Month",
        "manual_bank_reconciliation": "🛠 Manual Bank Reconciliation",
        "manual_bank_reconciliation_desc": "Use this to reconcile the system balance with the actual bank statement.",
        "select_building_reconciliation": "⚠️ Please select a specific building to perform reconciliation.",
        "performing_reconciliation": "ℹ️ Performing reconciliation for **{building_name}** (ID: {building_id})",
        "bank_balance_statement": "🏦 Bank Balance (from statement)",
        "system_net_balance": "**📊 System Net Balance:**",
        "adjustment_needed": "**🧮 Adjustment Needed:**",
        "note_for_adjustment": "📝 Note for adjustment",
        "submit_adjustment": "💾 Submit Adjustment",
        "adjustment_recorded": "✅ Adjustment transaction recorded.",
        "undo_last_reconciliation": "↩️ Undo Last Reconciliation",
        "last_reconciliation_removed": "✅ Last reconciliation entry was removed.",
        "no_reconciliation_entry": "ℹ️ No reconciliation entry found to delete.",
        "net_cash_flow_title": "🏦 Net Cash Flow by Month (Past 6 Months)",
        "baseline_threshold": "📉 Baseline Threshold (₪)",
        "baseline_label": "Baseline ₪{value}",
        "forecast_label": "Forecast",
        "cumulative_net_label": "Cumulative Net",
        "monthly_net_label": "Monthly Net",
        "forecast_net_label": "Forecast Net",
        "cumulative_forecast_label": "Cumulative Forecast",
        "paid_in_label": "Paid In",
        "paid_out_label": "Paid Out",
        "expected_amount_label": "Expected Amount",
        "total_expenses_label": "Total Expenses",
        "pending_expenses_label": "Pending Expenses",
        "paid_expenses_label": "Paid Expenses",
        "view_unpaid_expenses": "📋 View Unpaid Expenses",
        "no_unpaid_expenses": "🎉 No unpaid expenses found for the selected filters.",
        "view_unpaid_apartments": "👥 View Unpaid Apartments",
        "all_apartments_paid": "🎉 All apartments have paid.",
        "expense_breakdown": "💸 Expense Breakdown",
        "no_expenses_found": "No expenses found for this period.",
        "kpi_paid": "✅ Paid",
        "kpi_expenses": "💸 Expenses",
        "kpi_pending_expenses": "🕓 Pending Expenses",
        "kpi_left_to_collect": "Left To Collect",
        "special_transactions": "🏠 Special Transactions",
        "expected_net": "Expected Net",
        "half_year_summary": "Half-Year Summary",
        "half_year": "Half-Year",
        "expected_label": "Expected",
        "payments_by_month": "Tenant Payments by Month",
        "expenses_by_month": "Expenses by Month",
        "expected_end_period_net": "End of period expected net",
        "view_transactions_table": "📋 View Transactions Table",
        "edit_or_delete_transaction": "✏️ Edit or Delete Transaction",
        "select_transaction": "🕽️ Select a Transaction",
        "update": "📏 Update",
        "delete": "🔐 Delete",
        "transaction_updated": "Transaction updated.",
        "transaction_deleted": "Transaction deleted.",
        "select_transaction_prompt": "Please select a transaction from the list above.",
        "add_new_transaction": "➕ Add New Transaction",
        "select_apartment": "🏠 Select Apartment",
        "month_being_paid_for": "📆 Month Being Paid For",
        "payment_date_made": "💰 Date Payment Was Made",
        "add_transaction_btn": "Add Transaction",
        "no_active_resident": "⚠️ No active resident found for this apartment. Please set one in the Buildings page.",
        "transaction_added_for": "✅ Transaction added for {first_name} {last_name}.",
        "bulk_insert_transactions": "➕ Bulk Insert Transactions",
        "bulk_insert_hint": "Use this to insert transactions for multiple apartments that paid.",
        "no_charge_data": "⚠️ No charge data available.",
        "year_being_paid_for": "📅 Year Being Paid For",
        "months_being_paid_for": "🗓 Months Being Paid For",
        "payment_received_on": "💰 Payment Received On",
        "no_expected_charges_selected_months": "⚠️ No expected charges found for the selected months.",
        "all_apartments_paid_selected_months": "🎉 All apartments have paid for the selected months.",
        "select_apartments_and_months": "🏘 Select Apartments and Months",
        "select_apartments": "🏘 Select Apartments",
        "select_all_apartments": "Select All Apartments",
        "insert_transactions": "🚀 Insert Transactions",
        "some_transactions_skipped": "⚠️ Some transactions were skipped:",
        "please_select_at_least_one_month": "Please select at least one month.",
        "transactions_inserted": "✅ {count} transaction(s) inserted.",
        "import_transactions": "📥 Import Transactions",
        "download_template": "⬇️ Download Template",
        "upload_csv": "Upload CSV",
        "confirm_import": "✅ Confirm Import",
        "invalid_csv": "⚠️ Invalid CSV format.",
        "import_success": "✅ {count} transactions imported.",
        "import_expenses": "📥 Import Expenses",
        "import_expenses_success": "✅ {count} expenses imported.",
        "some_expenses_skipped": "⚠️ Some expenses were skipped:",
        "filter_by_receipt_id": "🔍 Filter by Receipt ID",
        "view_expenses_table": "📊 View Expenses Table",
        "building_id_label": "Building ID",
        "supplier_receipt_label": "Receipt",
        "building_label": "Building",
        "expense_id_label": "Expense ID",
        "transaction_id_label": "Transaction ID",
        "supplier_label": "Supplier",
        "receipt_id": "Receipt ID",
        "start_date": "Start Date",
        "end_date": "End Date",
        "total_cost": "Total Cost",
        "monthly_cost": "Monthly Cost",
        "number_of_payments": "Number of Payments",
        "status_label": "Status",
        "notes_label": "Notes",
        "expense_type": "Expense Type",
        "select_expense": "Select Expense",
        "user_overview": "User Overview",
        "total_users": "Total Users",
        "download_csv": "⬇️ Download CSV",
        "download_users_csv": "Download Users CSV",
        "download_my_data_csv": "Download My Data",
        "download_summary_pdf": "⬇️ Download Summary PDF",
        "issue_date": "Date of Issue",
        "live_sessions": "Live Sessions",
        "live_users_metric": "Live Users (past 5 min)",
        "no_active_users": "No active users in the last 5 minutes.",
        "edit_delete_reset_user": "Edit, Delete, or Reset User",
        "select_user_to_manage": "Select User to Manage",
        "role": "Role",
        "new_password_optional": "🔐 New Password (leave blank to keep current)",
        "update_user": "💾 Update User",
        "user_updated": "✅ User updated.",
        "reset_password": "🔁 Reset Password",
        "password_reset": "✅ Password reset.",
        "delete_user": "🗑 Delete User",
        "cannot_delete_admin": "❌ Cannot delete an admin user.",
        "cannot_delete_self": "❌ You cannot delete your own account.",
        "user_deleted": "⚠️ User deleted.",
        "assign_buildings_to_user": "Assign Buildings to User",
        "select_user": "Select User",
        "select_buildings": "Select Buildings",
        "no_buildings_assigned_user": "No buildings will be assigned to this user.",
        "save_assignments": "Save Assignments",
        "assignments_updated": "Assignments updated.",
        "create_new_user": "➕ Create New User",
        "onboarding_wizard": "🧭 Onboarding Wizard",
        "onboarding_info": "Start the guided setup wizard for a new user.",
        "start_onboarding_wizard": "🚀 Start Onboarding Wizard",
        "not_assigned_building_admin": "🚫 You were not assigned any building. Please contact an administrator.",
        "view_assigned_buildings": "🏢 View Assigned Buildings",
        "select_building_manage": "Select a building to manage",
        "view_set_active_residents": "👥 View & Set Active Residents",
        "residents_in_building": "Residents in {building}",
        "no_residents_found": "No residents found.",
        "click_set_active_hint": "Click 'Set Active' to mark a resident as currently occupying their apartment.",
        "apt_header": "Apt",
        "floor_header": "Floor",
        "name_header": "Name",
        "phone_label": "Phone",
        "first_name_label": "First Name",
        "last_name_label": "Last Name",
        "active_label": "Active",
        "set_active": "Active",
        "resident_now_active": "✅ {first_name} {last_name} is now active",
        "active_status": "Active",
        "update_monthly_fees_title": "💸 Update Monthly Fees and Generate Charges for a Year",
        "update_monthly_fees_desc": "Use this section to set apartment rates and generate expected charges for all months of a selected year.",
        "select_year": "Select Year",
        "choose_update_mode": "Choose Update Mode",
        "bulk_update": "Bulk Update",
        "individual_update": "Individual Update",
        "bulk_update_all_fees": "💼 Bulk Update All Apartment Fees",
        "new_monthly_fee": "💰 New Monthly Fee",
        "apply_bulk_update": "💾 Apply Bulk Update",
        "bulk_update_success": "✅ Updated all apartments with ₪{fee}",
        "individual_fee_updates": "✏️ Individual Apartment Fee Updates",
        "fee_label": "Fee",
        "update_fee_success": "✅ Updated fee for Apt {apartment}",
        "generate_expected_charges_for_year": "📆 Generate Expected Charges for All of {year}",
        "expected_charges_generated": "✅ Expected charges generated for all 12 months of {year}. Existing rows were skipped automatically.",
        "add_resident_expander": "➕ Add Resident",
        "no_apartments_found": "No apartments found in this building. Please add apartments before adding residents.",
        "add_resident_btn": "Add Resident",
        "resident_added": "Resident added.",
        "edit_resident_expander": "✏️ Edit Resident",
        "no_residents_available": "No residents available.",
        "select_resident": "Select Resident",
        "update_resident_btn": "Update Resident",
        "resident_updated": "Resident updated.",
        "delete_resident_expander": "🗑 Delete Resident",
        "no_residents_to_delete": "No residents to delete.",
        "select_resident_to_delete": "Select Resident to Delete",
        "delete_resident_btn": "Delete Resident",
        "resident_deleted": "Resident deleted.",
        "send_message_residents_expander": "✉️ Send Message to All Residents",
        "subject_label": "Subject",
        "message_body": "Message Body",
        "send_email_all_residents": "Send Email to All Residents",
        "emails_sent_residents": "Emails sent to all residents.",
        "add_new_building_expander": "➕ Add New Building",
        "building_name_label": "Building Name",
        "city_label": "City",
        "street_label": "Street",
        "home_number_label": "Home Number",
        "postal_code_label": "Postal Code",
        "building_code_label": "Building Code",
        "vaad_name_label": "Vaad Name",
        "bank_name_label": "Bank Name",
        "bank_branch_label": "Bank Branch",
        "bank_account_label": "Bank Account",
        "bank_number_label": "Bank Number",
        "vaad_representative_label": "Vaad Representative",
        "contact_phone_label": "Contact Phone",
        "contact_email_label": "Contact Email",
        "add_building_btn": "Add Building",
        "edit_building_expander": "✏️ Edit Building",
        "select_building_edit": "Select Building to Edit",
        "update_building_btn": "Update Building",
        "building_updated": "Building updated.",
        "bulk_add_apartments_expander": "➕ Bulk Add Apartments (Auto-Floor Assignment)",
        "bulk_add_apartments_desc": "Add a range of apartments and assign them to floors automatically.",
        "from_apartment_number": "🔢 From Apartment Number",
        "to_apartment_number": "🔢 To Apartment Number",
        "starting_floor": "🏢 Starting Floor",
        "apartments_per_floor": "📐 Apartments Per Floor",
        "submit_bulk_apartments": "➕ Submit Bulk Apartments",
        "apartments_added_success": "✅ Apartments {start} to {end} added. Apartment 0 ensured.",
        "delete_building_expander": "🗑 Delete Building",
        "select_building_delete": "Select Building to Delete",
        "delete_building_btn": "Delete Building",
        "first_time_setup_title": "🚀 First-Time Setup Wizard",
        "user_not_found": "User not found.",
        "update_contact_info": "👤 Update Your Contact Info",
        "step1_instruction": "Enter your email and choose a password so you can securely access the system.",
        "your_email_label": "📧 Your Email",
        "new_password_label": "🔐 New Password",
        "save_contact_info_btn": "💾 Save Contact Info",
        "contact_info_updated": "✅ Contact info updated.",
        "contact_info_step_completed": "✅ Contact info step completed.",
        "add_first_building": "🏢 Add Your First Building",
        "step2_instruction": "Provide basic address details. The building will automatically be linked to your account.",
        "building_added_assigned_you": "✅ Building added and assigned to you.",
        "building_step_completed": "✅ Building step completed.",
        "your_buildings_header": "📋 Your Buildings",
        "add_apartments_title": "🏠 Add Apartments",
        "step3_instruction": "Define apartment numbers and floors to quickly create all units.",
        "apartments_added": "✅ Apartments added.",
        "apartments_step_completed": "✅ Apartments step completed.",
        "no_apartments_step3_warning": "⚠️ No apartments found for this building. Please complete Step 3 (Add Apartments) first.",
        "back_btn": "⬅️ Back",
        "next_btn": "➡️ Next",
        "next_phase_btn": "➡️ Next Phase",
        "apartment_select_error": "Something went wrong selecting the apartment.",
        "residents_already_added": "✅ Residents already added for {apt_label}.",
        "delete_residents_for_apartment": "🗑️ Delete Residents for this Apartment",
        "residents_deleted": "Residents deleted.",
        "renter_details": "👤 Renter Details",
        "renter_first_name": "Renter First Name",
        "renter_last_name": "Renter Last Name",
        "renter_phone": "Renter Phone",
        "renter_email": "Renter Email",
        "owner_same_as_renter": "Owner is the same as Renter",
        "owner_details": "👤 Owner Details",
        "owner_first_name": "Owner First Name",
        "owner_last_name": "Owner Last Name",
        "owner_phone": "Owner Phone",
        "owner_email": "Owner Email",
        "add_residents_btn": "➕ Add Residents",
        "step4_instruction": "Fill in renter and owner information for each apartment.",
        "residents_added_for": "✅ Residents for {apt_label} added.",
        "summary_table_title": "🧾 Summary Table",
        "residents_step_completed": "✅ Residents step completed.",
        "set_active_residents_title": "who lives here ?",
        "step5_instruction": "Select the resident currently occupying each apartment to mark them active.",
        "set_active_resident_for_apartment": "✅ Set {name} active for apartment {apt_num}",
        "resident_now_active_for_apartment": "✅ {name} is now active for apartment {apt_num}",
        "active_resident_step_completed": "✅ Active resident step completed.",
        "set_monthly_fees_title": "💰 Set Monthly Fees",
        "step6_instruction": "Choose the monthly maintenance fee charged to every apartment.",
        "apply_fee_btn": "💾 Apply Fee",
        "fees_updated": "Fees updated.",
        "fees_step_completed": "✅ Fees step completed.",
        "add_transactions_title": "💳 Add Transactions",
        "step7_instruction": "Record an example payment from a resident.",
        "transactions_step_info": "This step can be skipped and completed later via the Transactions page.",
        "apartment_label": "Apartment",
        "charge_month_label": "Charge Month",
        "save_transaction_btn": "💾 Save Transaction",
        "transaction_added": "Transaction added.",
        "transactions_summary_title": "🧾 Transactions Summary",
        "transactions_step_completed": "✅ Transactions step marked as complete.",
        "add_expenses_title": "💸 Add Expenses",
        "step8_instruction": "Create an initial expense to track outgoing costs.",
        "expenses_step_info": "This step can be skipped and completed later via the Expenses page.",
        "building_supplier_warning": "You must add at least one building and one supplier before continuing.",
        "supplier_name": "Supplier Name",
        "supplier_id_label": "Supplier ID",
        "segment_label": "Segment",
        "add_supplier_expander": "➕ Add New Supplier",
        "edit_supplier_expander": "✏️ Edit Supplier",
        "delete_supplier_expander": "🗑 Delete Supplier",
        "new_name": "New Name",
        "new_expense_type": "New Expense Type",
        "new_segment": "New Segment",
        "update_supplier_btn": "Update Supplier",
        "no_suppliers_to_edit": "No suppliers to edit.",
        "select_supplier": "Select Supplier",
        "select_supplier_to_delete": "Select Supplier to Delete",
        "no_suppliers_to_delete": "No suppliers available to delete.",
        "supplier_management": "Supplier Management",
        "phone_for_building": "📱 Phone for {name}",
        "contact_email_for_building": "📨 Contact Email for {name}",
        "building_contact_info_title": "📞 Building Contact Info",
        "save_changes_btn": "💾 Save Changes",
        "profile_updated": "✅ Profile and building contacts updated.",
        "failed_to_update": "❌ Failed to update: {error}",
        "invoice_footer_preview": "🧾 Invoice Footer Preview",
        "in_building_footer_preview": "In building <u>{name}</u> this will appear as:",
        "unknown_building": "Unknown Building",
        "finish_setup_btn": "🏁 Finish Setup",
        "setup_complete_redirecting": "🎉 Setup complete! Redirecting to dashboard...",
        "save_expense_btn": "💾 Save Expense",
        "expense_summary_title": "📋 Expense Summary",
        "supplier_receipt_id": "Supplier Receipt ID",
        "Num_payments_label":"In Payments",
        "add_residents_title": "Add residents",
        "gpt_assistant": "Ai Assistant",
        "ask_gpt": "Ask GPT",
        "thinking": "Thinking...",
        "attach_documents": "Attach Document(s)",
        "documents": "Documents",
        "no_documents": "No documents found.",
        "document_deleted": "Document deleted.",
        "upload_documents": "Upload Documents",
        "documents_uploaded": "Documents uploaded.",
        "storage_action_failed": "Failed to process document: {error}",
        "support_tickets": "Support Tickets",
        "no_tickets": "No tickets found.",
        "submit_ticket": "Submit Ticket",
        "support_ticket_admin": "Support Ticket Admin",
        "open_tickets": "Open Tickets",
        "select_ticket": "Select Ticket",
        "update_ticket_status": "Update Status",
        "ticket_status_updated": "Ticket status updated.",
        "delete_ticket": "Delete Ticket",
        "ticket_deleted": "Ticket deleted.",
        "no_open_tickets": "No open tickets.",
        "close_support_page": "⬅️ Close Support Page"

    },
    "he": {
        "dashboard": "לוח בקרה",
        "buildings": "בניינים",
        "invoices": "חשבוניות",
        "suppliers": "ספקים",
        "expenses": "הוצאות",
        "logged_in_as": "מחובר כ",
        "stop_server": "🛑 עצור שרת",
        "logout": "🚪 התנתק",
        "send_invoice_subject": "חשבונית עבור תשלום",
        "send_invoice_body": "דייר יקר,\n\nמצורפת חשבונית עבור התשלום שלך.\n\nבברכה,\nועד הבית",
        "invoice_email_subject": "📄 חשבונית #{invoice_id} מוועד הבית",
        "invoice_email_body": "{resident_name} שלום,\n\nמצורפת קבלה על התשלום שביצעתם לוועד הבית.",
        "resident": "דייר",
        "apartment": "דירה",
        "payment_date": "תאריך תשלום",
        "amount_paid": "סכום ששולם",
        "thank_you": "תודה על התשלום!",
        "receipt": "קבלה מס'",
        "date": "תאריך",
        "resident_name": "שם הדייר",
        "payment_method": "אמצעי תשלום",
        "for_month": "תשלום עבור",
        "description": "תיאור",
        "amount": "סכום",
        "line_item": "ועד בית",
        "total_paid": 'סה"כ ששולם',
        "thanks": "תודה רבה על התשלום!",
        "contact": "ליצירת קשר",
        "view_invoice": "👁️ הצג חשבונית",
        "send_invoice": "📤 שלח חשבונית",
        "download_invoice": "⬇️ הורד חשבונית",
        "invoice_sent_to": "חשבונית מספר {invoice_id} נשלחה ל-{email}",
        "invoice_sent_short": "📧 נשלח",
        "filter_by_building": "🏢 סינון לפי בניין",
        "filter_by_status": "📌 סינון לפי סטטוס",
        "filter_by_expense_type": "📂 סינון לפי סוג הוצאה",
        "filter_by_start_date": "📅 מתאריך התחלה",
        "add_expense": "הוסף הוצאה",
        "edit_expense": "ערוך הוצאה",
        "delete_expense": "מחק הוצאה",
        "add_supplier": "הוסף ספק",
        "edit_supplier": "ערוך ספק",
        "delete_supplier": "מחק ספק",
        "view_as_user": "👤 תצוגת משתמש",
        "view_as_admin": "👤 תצוגת מנהל",
        "admin_panel": "🔐 ממשק ניהול",
        "back_to_app": "⬅️ חזרה לאפליקציה",
        "assign_buildings": "🏢 שיוך לבניינים",
        "create_account": "➕ צור משתמש חדש",
        "building_added": "הבניין נוסף!",
        "building_deleted": "הבניין '{building}' נמחק בהצלחה!",
        "expense_added": "הוצאה נוספה בהצלחה.",
        "expense_updated": "הוצאה עודכנה.",
        "expense_deleted": "הוצאה נמחקה.",
        "supplier_added": "הספק נוסף!",
        "supplier_updated": "הספק עודכן.",
        "supplier_deleted": "הספק נמחק.",
        "login_title": "התחברות",
        "signup_title": "הרשמה",
        "username": "שם משתמש",
        "new_username": "שם משתמש חדש",
        "new_password": "סיסמה חדשה",
        "password": "סיסמה",
        "email": "אימייל",
        "user_created": "המשתמש נוצר! אנא התחבר.",
        "fill_all_fields": "נא למלא את כל השדות.",
        "invalid_credentials": "שם משתמש או סיסמה שגויים",
        "welcome_user": "ברוך הבא, {username}",
        "create_account_btn": "צור חשבון",
        "login_btn": "התחברות",
        "months": [
            "ינואר", "פברואר", "מרץ", "אפריל", "מאי", "יוני",
            "יולי", "אוגוסט", "ספטמבר", "אוקטובר", "נובמבר", "דצמבר"
        ],"your_balance": "היתרה שלך","total_amount_paid": "סה\"כ שולם",
        "transactions": "תשלומי דיירים",
        "my_profile": "הפרופיל שלי",
        "support": "תמיכה",
        "reports": "דוחות",
        "produce_report": "הפק דוח",
        "report_type": "סוג דוח",
        "full_report": "דוח מלא",
        "transactions_only": "תשלומים בלבד",
        "expenses_only": "הוצאות בלבד",
        "net_balance": "יתרה נטו",
        "send_invoices_title": "שליחת חשבוניות",
        "select_building": "בחר בניין",
        "please_select_building": "אנא בחר בניין כדי להציג או לשלוח חשבוניות.",
        "year": "שנה",
        "month": "חודש",
        "quarter": "רבעון",
        "select_apartments_send": "בחר דירות לשליחת חשבוניות",
        "send_selected_invoices": "שלח חשבוניות נבחרות",
        "please_select_apartment": "אנא בחר לפחות דירה אחת.",
        "invoices_sent_success": "{count} חשבוניות נשלחו בהצלחה.",
        "no_paid_transactions": "לא נמצאו תשלומים עבור הסינון שנבחר.",
        "paid_transactions": "תשלומים ששולמו",
        "transactions_management": "ניהול תשלומים",
        "total_expense_amount": "סך כל ההוצאות",
        "cumulative_value": "ערך מצטבר",
        "no_expenses_match": "אין הוצאות תואמות לסינון הנבחר.",
        "app_title": "🏠 אפליקציית ניהול דירות",
        "app_subtitle": "הנתונים והסיכום הכספי העדכניים שלך.",
        "no_buildings_assigned": "⚠️ לא הוקצו בניינים לחשבונך.",
        "from_year": "משנה",
        "from_month": "מחודש",
        "to_year": "עד שנה",
        "to_month": "עד חודש",
        "manual_bank_reconciliation": "🛠 התאמת בנק ידנית",
        "manual_bank_reconciliation_desc": "השתמש בזה כדי להתאים את יתרת המערכת לדפי הבנק.",
        "select_building_reconciliation": "⚠️ אנא בחר בניין ספציפי לביצוע התאמה.",
        "performing_reconciliation": "ℹ️ מבצע התאמה עבור **{building_name}** (מזהה {building_id})",
        "bank_balance_statement": "🏦 יתרת בנק (מתדפיס)",
        "system_net_balance": "**📊 יתרת מערכת:**",
        "adjustment_needed": "**🧮 התאמה נדרשת:**",
        "note_for_adjustment": "📝 הערה להתאמה",
        "submit_adjustment": "💾 בצע התאמה",
        "adjustment_recorded": "✅ עסקת ההתאמה נרשמה.",
        "undo_last_reconciliation": "↩️ בטל התאמה אחרונה",
        "last_reconciliation_removed": "✅ רשומת ההתאמה האחרונה נמחקה.",
        "no_reconciliation_entry": "ℹ️ לא נמצאה רשומת התאמה למחיקה.",
        "net_cash_flow_title": "🏦 תזרים מזומנים חודשי (6 החודשים האחרונים)",
        "baseline_threshold": "📉 סף בסיס (₪)",
        "baseline_label": "בסיס ₪{value}",
        "forecast_label": "תחזית",
        "cumulative_net_label": "יתרה מצטברת",
        "monthly_net_label": "נטו חודשי",
        "forecast_net_label": "נטו חזוי",
        "cumulative_forecast_label": "מצטבר חזוי",
        "paid_in_label": "התקבל",
        "paid_out_label": "שולם החוצה",
        "expected_amount_label": "סכום צפוי",
        "total_expenses_label": "סך כל ההוצאות",
        "pending_expenses_label": "הוצאות ממתינות",
        "paid_expenses_label": "הוצאות ששולמו",
        "view_unpaid_expenses": "📋 הצג הוצאות שלא שולמו",
        "no_unpaid_expenses": "🎉 לא נמצאו הוצאות שלא שולמו לסינון זה.",
        "view_unpaid_apartments": "👥 הצג דירות שלא שילמו",
        "all_apartments_paid": "🎉 כל הדירות שילמו.",
        "expense_breakdown": "💸 פירוט הוצאות",
        "no_expenses_found": "לא נמצאו הוצאות לתקופה זו.",
        "kpi_paid": "✅ שולם",
        "kpi_expenses": "💸 הוצאות",
        "kpi_pending_expenses": "🕓 הוצאות ממתינות",
        "kpi_left_to_collect": "נותר לגבות",
        "special_transactions": "🏠 עסקאות מיוחדות",
        "expected_net": "יתרה צפויה",
        "half_year_summary": "סיכום חצי שנתי",
        "half_year": "חצי שנה",
        "expected_label": "צפוי",
        "payments_by_month": "תשלומי דיירים לפי חודש",
        "expenses_by_month": "הוצאות לפי חודש",
        "expected_end_period_net": "בסוף התקופה הנטו החזוי",
        "view_transactions_table": "📋 הצג טבלת תשלומים",
        "edit_or_delete_transaction": "✏️ ערוך או מחק תשלום",
        "select_transaction": "🕽️ בחר תשלום",
        "update": "📏 עדכן",
        "delete": "🔐 מחק",
        "transaction_updated": "התשלום עודכן.",
        "transaction_deleted": "התשלום נמחק.",
        "select_transaction_prompt": "אנא בחר תשלום מהרשימה למעלה.",
        "add_new_transaction": "➕ הוסף תשלום חדש",
        "select_apartment": "🏠 בחר דירה",
        "month_being_paid_for": "📆 חודש בגינו משולם",
        "payment_date_made": "💰 תאריך התשלום",
        "add_transaction_btn": "הוסף תשלום",
        "no_active_resident": "⚠️ לא נמצא דייר פעיל לדירה זו. אנא קבע אחד בדף הבניינים.",
        "transaction_added_for": "✅ נוספה עסקה עבור {first_name} {last_name}.",
        "bulk_insert_transactions": "➕ הוסף תשלומים בכמות",
        "bulk_insert_hint": "השתמש בזה כדי להזין תשלומים עבור מספר דירות ששילמו.",
        "no_charge_data": "⚠️ אין נתוני חיוב זמינים.",
        "year_being_paid_for": "📅 שנת תשלום",
        "months_being_paid_for": "🗓 חודשים בגינם משולם",
        "payment_received_on": "💰 תשלום התקבל ב-",
        "no_expected_charges_selected_months": "⚠️ לא נמצאו חיובים צפויים לחודשים שבחרת.",
        "all_apartments_paid_selected_months": "🎉 כל הדירות שילמו עבור החודשים שנבחרו.",
        "select_apartments_and_months": "🏘 בחר דירות וחודשים",
        "select_apartments": "🏘 בחר דירות",
        "select_all_apartments": "בחר את כל הדירות",
        "insert_transactions": "🚀 הוסף תשלומים",
        "some_transactions_skipped": "⚠️ חלק מהתשלומים דולגו:",
        "please_select_at_least_one_month": "אנא בחר לפחות חודש אחד.",
        "transactions_inserted": "✅ הוכנסו {count} תשלומים",
        "import_transactions": "📥 ייבוא תשלומים",
        "download_template": "⬇️ הורד תבנית",
        "upload_csv": "העלה קובץ CSV",
        "confirm_import": "✅ אישור ייבוא",
        "invalid_csv": "⚠️ פורמט CSV לא תקין.",
        "import_success": "✅ יובאו {count} תשלומים.",
        "import_expenses": "📥 ייבוא הוצאות",
        "import_expenses_success": "✅ יובאו {count} הוצאות.",
        "some_expenses_skipped": "⚠️ חלק מההוצאות דולגו:",
        "filter_by_receipt_id": "🔍 סינון לפי מספר קבלה",
        "view_expenses_table": "📊 הצג טבלת הוצאות",
        "building_id_label": "מזהה בניין",
        "building_label": "בניין",
        "expense_id_label": "מזהה הוצאה",
        "transaction_id_label": "מזהה תשלום",
        "supplier_receipt_label": "חשבונית",
        "Num_payments_label":"מספר תשלומים",
        "supplier_label": "ספק",
        "receipt_id": "מספר קבלה",
        "start_date": "תאריך התחלה",
        "end_date": "תאריך סיום",
        "total_cost": "עלות כוללת",
        "monthly_cost": "עלות חודשית",
        "number_of_payments": "מספר תשלומים",
        "status_label": "סטטוס",
        "notes_label": "הערות",
        "expense_type": "סוג הוצאה",
        "select_expense": "בחר הוצאה",
        "user_overview": "סקירת משתמשים",
        "total_users": "סה\"כ משתמשים",
        "download_csv": "⬇️ הורד CSV",
        "download_users_csv": "הורד קובץ משתמשים CSV",
        "download_my_data_csv": "הורד את הנתונים שלי",
        "download_summary_pdf": "⬇️ הורד דו\"ח PDF",
        "issue_date": "תאריך הפקה",
        "live_sessions": "משתמשים פעילים",
        "live_users_metric": "משתמשים פעילים (5 דק׳ אחרונות)",
        "no_active_users": "אין משתמשים פעילים ב-5 הדקות האחרונות.",
        "edit_delete_reset_user": "ערוך, מחק או אפס משתמש",
        "select_user_to_manage": "בחר משתמש לניהול",
        "role": "תפקיד",
        "new_password_optional": "🔐 סיסמה חדשה (השאר ריק לשמירת הנוכחית)",
        "update_user": "💾 עדכן משתמש",
        "user_updated": "✅ המשתמש עודכן.",
        "reset_password": "🔁 אפס סיסמה",
        "password_reset": "✅ הסיסמה אופסה.",
        "delete_user": "🗑 מחק משתמש",
        "cannot_delete_admin": "❌ לא ניתן למחוק משתמש מנהל.",
        "cannot_delete_self": "❌ אינך יכול למחוק את חשבונך.",
        "user_deleted": "⚠️ המשתמש נמחק.",
        "assign_buildings_to_user": "שיוך בניינים למשתמש",
        "select_user": "בחר משתמש",
        "select_buildings": "בחר בניינים",
        "no_buildings_assigned_user": "לא יוקצו בניינים למשתמש זה.",
        "save_assignments": "שמור שיוכים",
        "assignments_updated": "השיוכים עודכנו.",
        "create_new_user": "➕ צור משתמש חדש",
        "onboarding_wizard": "🧭 אשף התחלת עבודה",
        "onboarding_info": "התחל אשף הגדרת משתמש חדש.",
        "start_onboarding_wizard": "🚀 התחל אשף התחלת עבודה",
        "not_assigned_building_admin": "🚫 לא שוייכת לשום בניין. אנא פנה למנהל.",
        "view_assigned_buildings": "🏢 הצג בניינים משוייכים",
        "select_building_manage": "בחר בניין לניהול",
        "view_set_active_residents": "👥 הצג וקבע דיירים פעילים",
        "residents_in_building": "דיירי {building}",
        "no_residents_found": "לא נמצאו דיירים.",
        "click_set_active_hint": "לחצו 'קבע פעיל' כדי לסמן דייר כמתגורר כעת בדירה.",
        "apt_header": "דירה",
        "floor_header": "קומה",
        "name_header": "שם",
        "phone_label": "טלפון",
        "first_name_label": "שם פרטי",
        "last_name_label": "שם משפחה",
        "active_label": "פעיל",
        "set_active": "קבע",
        "resident_now_active": "✅ {first_name} {last_name} פעיל כעת",
        "active_status": "פעיל",
        "update_monthly_fees_title": "💸 עדכון דמי חיוב חודשי ויצירת חיובים ",
        "update_monthly_fees_desc": "השתמשו בחלק זה כדי לקבוע עלויות דירה וליצור חיובים צפויים לכל חודשי השנה שנבחרה.",
        "select_year": "בחר שנה",
        "choose_update_mode": "בחר מצב עדכון",
        "bulk_update": "עדכון גורף",
        "individual_update": "עדכון יחידני",
        "bulk_update_all_fees": "💼 עדכון גורף לכל דמי הדירות",
        "new_monthly_fee": "💰 דמי חודשיים חדשים",
        "apply_bulk_update": "💾 בצע עדכון גורף",
        "bulk_update_success": "✅ עודכנו כל הדירות ל־₪{fee}",
        "individual_fee_updates": "✏️ עדכון דמי דירה פרטניים",
        "fee_label": "תשלום",
        "update_fee_success": "✅ עודכן תשלום עבור דירה {apartment}",
        "generate_expected_charges_for_year": "📆 צור חיובים צפויים לכל שנת {year}",
        "expected_charges_generated": "✅ חיובים צפויים נוצרו לכל 12 החודשים של {year}. רשומות קיימות דולגו אוטומטית.",
        "add_resident_expander": "➕ הוסף דייר",
        "no_apartments_found": "לא נמצאו דירות בבניין זה. אנא הוסף דירות לפני הוספת דיירים.",
        "add_resident_btn": "הוסף דייר",
        "resident_added": "הדייר נוסף.",
        "edit_resident_expander": "✏️ ערוך דייר",
        "no_residents_available": "אין דיירים זמינים.",
        "select_resident": "בחר דייר",
        "update_resident_btn": "עדכן דייר",
        "resident_updated": "הדייר עודכן.",
        "delete_resident_expander": "🗑 מחק דייר",
        "no_residents_to_delete": "אין דיירים למחיקה.",
        "select_resident_to_delete": "בחר דייר למחיקה",
        "delete_resident_btn": "מחק דייר",
        "resident_deleted": "הדייר נמחק.",
        "send_message_residents_expander": "✉️ שלח הודעה לכל הדיירים",
        "subject_label": "נושא",
        "message_body": "תוכן ההודעה",
        "send_email_all_residents": "שלח אימייל לכל הדיירים",
        "emails_sent_residents": "האימיילים נשלחו לכל הדיירים.",
        "add_new_building_expander": "➕ הוסף בניין חדש",
        "building_name_label": "שם בניין",
        "city_label": "עיר",
        "street_label": "רחוב",
        "home_number_label": "מספר בית",
        "postal_code_label": "מיקוד",
        "building_code_label": "קוד בניין",
        "vaad_name_label": "שם הוועד",
        "bank_name_label": "שם הבנק",
        "bank_branch_label": "סניף בנק",
        "bank_account_label": "חשבון בנק",
        "bank_number_label": "מספר בנק",
        "vaad_representative_label": "נציג ועד",
        "contact_phone_label": "טלפון ליצירת קשר",
        "contact_email_label": "אימייל ליצירת קשר",
        "add_building_btn": "הוסף בניין",
        "edit_building_expander": "✏️ ערוך בניין",
        "select_building_edit": "בחר בניין לעריכה",
        "update_building_btn": "עדכן בניין",
        "building_updated": "הבניין עודכן.",
        "bulk_add_apartments_expander": "➕ הוספת דירות בכמות (שיוך אוטומטי לקומות)",
        "bulk_add_apartments_desc": "הוסף טווח דירות ושייך אותן לקומות אוטומטית.",
        "from_apartment_number": "🔢 מדירת מספר",
        "to_apartment_number": "🔢 עד דירת מספר",
        "starting_floor": "🏢 קומה התחלתית",
        "apartments_per_floor": "📐 דירות בכל קומה",
        "submit_bulk_apartments": "➕ הוסף דירות",
        "apartments_added_success": "✅ הדירות {start} עד {end} נוספו. דירה 0 הובטחה.",
        "delete_building_expander": "🗑 מחק בניין",
        "select_building_delete": "בחר בניין למחיקה",
        "delete_building_btn": "מחק בניין",
        "first_time_setup_title": "🚀 אשף התחלה ראשונה",
        "user_not_found": "המשתמש לא נמצא.",
        "update_contact_info": "👤 עדכן פרטי קשר",
        "step1_instruction": "הכניסו את האימייל ובחרו סיסמה כדי שהחשבון יהיה מאובטח.",
        "your_email_label": "📧 האימייל שלך",
        "new_password_label": "🔐 סיסמה חדשה",
        "save_contact_info_btn": "💾 שמור פרטי קשר",
        "contact_info_updated": "✅ פרטי הקשר עודכנו.",
        "contact_info_step_completed": "✅ שלב פרטי הקשר הושלם.",
        "add_first_building": "🏢 הוסף את הבניין הראשון שלך",
        "step2_instruction": "הוסיפו פרטי כתובת בסיסיים והבניין ישויך אוטומטית לחשבונכם.",
        "building_added_assigned_you": "✅ הבניין נוסף והוקצה לך.",
        "building_step_completed": "✅ שלב הבניין הושלם.",
        "your_buildings_header": "📋 הבניינים שלך",
        "add_apartments_title": "🏠 הוסף דירות",
        "step3_instruction": "הגדירו טווחי דירות ומספר קומות ליצירה מהירה של היחידות.",
        "apartments_added": "✅ הדירות נוספו.",
        "apartments_step_completed": "✅ שלב הדירות הושלם.",
        "no_apartments_step3_warning": "⚠️ לא נמצאו דירות בבניין זה. אנא השלם את שלב 3 (הוסף דירות) קודם.",
        "back_btn": "⬅️ חזרה",
        "next_btn": "➡️ הבא",
        "next_phase_btn": "➡️ שלב הבא",
        "apartment_select_error": "שגיאה בבחירת הדירה.",
        "residents_already_added": "✅ דיירים כבר נוספו עבור {apt_label}.",
        "delete_residents_for_apartment": "🗑️ מחק דיירים עבור דירה זו",
        "residents_deleted": "הדיירים נמחקו.",
        "renter_details": "👤 פרטי שוכר",
        "renter_first_name": "שם פרטי של שוכר",
        "renter_last_name": "שם משפחה של שוכר",
        "renter_phone": "טלפון שוכר",
        "renter_email": "אימייל שוכר",
        "owner_same_as_renter": "הבעלים הוא גם השוכר",
        "owner_details": "👤 פרטי בעלים",
        "owner_first_name": "שם פרטי של בעלים",
        "owner_last_name": "שם משפחה של בעלים",
        "owner_phone": "טלפון בעלים",
        "owner_email": "אימייל בעלים",
        "add_residents_btn": "➕ הוסף דיירים",
        "step4_instruction": "הזינו פרטי שוכר ובעלים לכל דירה.",
        "residents_added_for": "✅ דיירים עבור {apt_label} נוספו.",
        "summary_table_title": "🧾 טבלת סיכום",
        "residents_step_completed": "✅ שלב הדיירים הושלם.",
        "set_active_residents_title": "מי מתגורר בנכס?",
        "step5_instruction": "בחרו את הדייר הפעיל בכל דירה.",
        "set_active_resident_for_apartment": "✅ קבע את {name} פעיל לדירה {apt_num}",
        "resident_now_active_for_apartment": "✅ {name} פעיל כעת לדירה {apt_num}",
        "active_resident_step_completed": "✅ שלב הדייר הפעיל הושלם.",
        "set_monthly_fees_title": "💰 קבע דמי חודשיים",
        "step6_instruction": "קבעו את דמי הועד החודשיים לכל דירה.",
        "apply_fee_btn": "💾 החל תשלום",
        "fees_updated": "החיובים עודכנו.",
        "fees_step_completed": "✅ שלב החיובים הושלם.",
        "add_transactions_title": "💳 הוסף עסקאות",
        "step7_instruction": "הוסיפו דוגמה לתשלום מדייר.",
        "transactions_step_info": "ניתן לדלג על שלב זה ולבצעו מאוחר יותר דרך עמוד העסקאות.",
        "apartment_label": "דירה",
        "charge_month_label": "חודש חיוב",
        "save_transaction_btn": "💾 שמור עסקה",
        "transaction_added": "העסקה נוספה.",
        "transactions_summary_title": "🧾 סיכום עסקאות",
        "transactions_step_completed": "✅ שלב העסקאות סומן כהושלם.",
        "add_expenses_title": "💸 הוסף הוצאות",
        "step8_instruction": "צרו הוצאה ראשונית למעקב אחר העלויות.",
        "expenses_step_info": "ניתן לדלג על שלב זה ולבצעו מאוחר יותר דרך עמוד ההוצאות.",
        "building_supplier_warning": "יש להוסיף לפחות בניין אחד וספק אחד לפני המשך.",
        "supplier_name": "שם הספק",
        "supplier_id_label": "מזהה ספק",
        "segment_label": "קטגוריה",
        "add_supplier_expander": "➕ הוסף ספק חדש",
        "edit_supplier_expander": "✏️ ערוך ספק",
        "delete_supplier_expander": "🗑 מחק ספק",
        "new_name": "שם חדש",
        "new_expense_type": "סוג הוצאה חדש",
        "new_segment": "קטגוריה חדשה",
        "update_supplier_btn": "עדכן ספק",
        "no_suppliers_to_edit": "אין ספקים לעריכה.",
        "select_supplier": "בחר ספק",
        "select_supplier_to_delete": "בחר ספק למחיקה",
        "no_suppliers_to_delete": "אין ספקים זמינים למחיקה.",
        "supplier_management": "ניהול ספקים",
        "phone_for_building": "📱 טלפון עבור {name}",
        "contact_email_for_building": "📨 אימייל ליצירת קשר עבור {name}",
        "building_contact_info_title": "📞 פרטי קשר לבניין",
        "save_changes_btn": "💾 שמור שינויים",
        "profile_updated": "✅ הפרופיל ופרטי יצירת הקשר בבניין עודכנו.",
        "failed_to_update": "❌ נכשל העדכון: {error}",
        "invoice_footer_preview": "🧾 תצוגה מקדימה של כותרת חשבונית",
        "in_building_footer_preview": "בבניין <u>{name}</u> זה יופיע כך:",
        "unknown_building": "בניין לא ידוע",
        "finish_setup_btn": "🏁 סיום ההתקנה",
        "setup_complete_redirecting": "🎉 ההגדרה הושלמה! מעבר ללוח הבקרה...",
        "save_expense_btn": "💾 שמור הוצאה",
        "expense_summary_title": "📋 סיכום הוצאות",
        "supplier_receipt_id": "מספר קבלה מספק",
        "add_residents_title":"הוספת דיירים",
        "gpt_assistant": "עוזר AI",
        "ask_gpt": "שאל אותי כל דבר ",
        "thinking": "חושב...",
        "attach_documents": "צרף מסמכים",
        "documents": "מסמכים",
        "no_documents": "לא נמצאו מסמכים.",
        "document_deleted": "המסמך נמחק.",
        "upload_documents": "העלה מסמכים",
        "documents_uploaded": "המסמכים הועלו.",
        "storage_action_failed": "הפעולה באחסון נכשלה: {error}",
        "support_tickets": "פניות תמיכה",
        "no_tickets": "לא נמצאו פניות.",
        "submit_ticket": "שלח פנייה",
        "support_ticket_admin": "ניהול פניות", 
        "open_tickets": "פניות פתוחות",
        "select_ticket": "בחר פנייה",
        "update_ticket_status": "עדכן סטטוס",
        "ticket_status_updated": "הסטטוס עודכן.",
        "delete_ticket": "מחק פנייה",
        "ticket_deleted": "הפנייה נמחקה.",
        "no_open_tickets": "אין פניות פתוחות",
        "close_support_page": "סגור עמוד תמיכה"
    }
}


def get_translation(lang):
    """Return a translation lookup function for the given language."""
    def _(key):
        return translations.get(lang, {}).get(key, translations["en"].get(key, key))
    return _


payment_method_map = {
    "cash": {"en": "Cash", "he": "מזומן"},
    "credit": {"en": "Credit", "he": "אשראי"},
    "check": {"en": "Check", "he": "צ'ק"},
    "bank transfer": {"en": "Bank Transfer", "he": "העברה בנקאית"},
    "other": {"en": "Other", "he": "אחר"},
}


def translate_payment_method(method, lang):
    """Translate common payment method strings based on language."""
    if not method:
        return method
    key = str(method).strip().lower()
    return payment_method_map.get(key, {}).get(lang, method)
